-- No schema change.
--
-- This migration was generated on Windows against tables that had already been
-- renamed to tbl_*. On the Linux server those tables still have their original
-- names (communication_batch, fleet_registration, fleet_reg_details, ...) until
-- 20261003080000_fleet_detail_operator runs. The first ALTER failed there with
-- MySQL 1146, so this migration applied nothing.
--
-- The unique index it described is created after the rename by
-- 20261003133000_fleet_appointment_date.
SELECT 1;
