/**
 * Seed / upsert the seven fixed roles with default labels, jurisdiction, and permissions.
 *
 *   npm run seed:roles-table
 */
import 'dotenv/config'
import { prisma } from '../db.js'

const ROLES = [
  {
    code: 'SECRETARY',
    label: 'Secretary',
    jurisdiction: 'section',
    can_appraisals: true,
    can_financial_years: false,
    can_organization: false,
    can_personnel: false,
    can_allowances: false,
    can_allowance_types: false,
    can_allowance_catalog: false,
    can_allowance_rates: false,
    can_allowance_allocations: false,
    can_position_keywords: false,
    can_allowance_matrix: false,
    can_validate: false,
    can_demote_classification: false,
    can_letter_cc: false,
    can_decision_matrix: false,
    can_through_officers: false,
    can_import_history: false,
    can_export_history: false,
    can_users: false,
    can_roles: false,
  },
  {
    code: 'FIELD_ASSISTANT',
    label: 'Field Assistant',
    jurisdiction: 'section',
    can_appraisals: true,
    can_financial_years: false,
    can_organization: false,
    can_personnel: false,
    can_allowances: false,
    can_allowance_types: false,
    can_allowance_catalog: false,
    can_allowance_rates: false,
    can_allowance_allocations: false,
    can_position_keywords: false,
    can_allowance_matrix: false,
    can_validate: false,
    can_demote_classification: false,
    can_letter_cc: false,
    can_decision_matrix: false,
    can_through_officers: false,
    can_import_history: false,
    can_export_history: false,
    can_users: false,
    can_roles: false,
  },
  {
    code: 'ADMIN_ASSISTANT',
    label: 'Administrative Assistant',
    jurisdiction: 'section',
    can_appraisals: true,
    can_financial_years: false,
    can_organization: false,
    can_personnel: false,
    can_allowances: false,
    can_allowance_types: false,
    can_allowance_catalog: false,
    can_allowance_rates: false,
    can_allowance_allocations: false,
    can_position_keywords: false,
    can_allowance_matrix: false,
    can_validate: false,
    can_demote_classification: false,
    can_letter_cc: false,
    can_decision_matrix: false,
    can_through_officers: false,
    can_import_history: false,
    can_export_history: false,
    can_users: false,
    can_roles: false,
  },
  {
    code: 'HR_OFFICER',
    label: 'Human Resource Officer',
    jurisdiction: 'unit',
    can_appraisals: true,
    can_financial_years: false,
    can_organization: false,
    can_personnel: false,
    can_allowances: false,
    can_allowance_types: false,
    can_allowance_catalog: false,
    can_allowance_rates: false,
    can_allowance_allocations: false,
    can_position_keywords: false,
    can_allowance_matrix: false,
    can_validate: false,
    can_demote_classification: false,
    can_letter_cc: false,
    can_decision_matrix: false,
    can_through_officers: false,
    can_import_history: false,
    can_export_history: false,
    can_users: false,
    can_roles: false,
  },
  {
    code: 'HR_MANAGER',
    label: "Manager Human Resources Dev't Services",
    jurisdiction: 'group',
    can_appraisals: true,
    can_financial_years: false,
    can_organization: false,
    can_personnel: false,
    can_allowances: false,
    can_allowance_types: false,
    can_allowance_catalog: false,
    can_allowance_rates: false,
    can_allowance_allocations: false,
    can_position_keywords: false,
    can_allowance_matrix: false,
    can_validate: false,
    can_demote_classification: false,
    can_letter_cc: false,
    can_decision_matrix: false,
    can_through_officers: false,
    can_import_history: false,
    can_export_history: false,
    can_users: false,
    can_roles: false,
  },
  {
    code: 'HR_DIRECTOR',
    label: 'Director Human Resources',
    jurisdiction: 'group',
    can_appraisals: true,
    can_financial_years: false,
    can_organization: false,
    can_personnel: false,
    can_allowances: false,
    can_allowance_types: false,
    can_allowance_catalog: false,
    can_allowance_rates: false,
    can_allowance_allocations: false,
    can_position_keywords: false,
    can_allowance_matrix: false,
    can_validate: false,
    can_demote_classification: true,
    can_letter_cc: false,
    can_decision_matrix: false,
    can_through_officers: false,
    can_import_history: false,
    can_export_history: false,
    can_users: false,
    can_roles: false,
  },
  {
    code: 'ADMINISTRATOR',
    label: 'Administrator',
    jurisdiction: 'all',
    can_appraisals: true,
    can_financial_years: true,
    can_organization: true,
    can_personnel: true,
    can_allowances: true,
    can_allowance_types: true,
    can_allowance_catalog: true,
    can_allowance_rates: true,
    can_allowance_allocations: true,
    can_position_keywords: true,
    can_allowance_matrix: true,
    can_validate: true,
    can_demote_classification: true,
    can_letter_cc: true,
    can_decision_matrix: true,
    can_through_officers: true,
    can_import_history: true,
    can_export_history: true,
    can_users: true,
    can_roles: true,
  },
] as const

for (const role of ROLES) {
  await prisma.tbl_roles.upsert({
    where: { code: role.code },
    create: { ...role },
    update: {
      label: role.label,
      jurisdiction: role.jurisdiction,
      can_appraisals: role.can_appraisals,
      can_financial_years: role.can_financial_years,
      can_organization: role.can_organization,
      can_personnel: role.can_personnel,
      can_allowances: role.can_allowances,
      can_allowance_types: role.can_allowance_types,
      can_allowance_catalog: role.can_allowance_catalog,
      can_allowance_rates: role.can_allowance_rates,
      can_allowance_allocations: role.can_allowance_allocations,
      can_position_keywords: role.can_position_keywords,
      can_allowance_matrix: role.can_allowance_matrix,
      can_validate: role.can_validate,
      can_demote_classification: role.can_demote_classification,
      can_letter_cc: role.can_letter_cc,
      can_decision_matrix: role.can_decision_matrix,
      can_through_officers: role.can_through_officers,
      can_import_history: role.can_import_history,
      can_export_history: role.can_export_history,
      can_users: role.can_users,
      can_roles: role.can_roles,
    },
  })
}

console.log(`Upserted ${ROLES.length} role(s)`)
await prisma.$disconnect()
